pool:
  vmImage: windows-latest

steps:
- powershell: |
    & C:\vcpkg\bootstrap-vcpkg.bat
    & C:\vcpkg\vcpkg.exe integrate install
  displayName: 'Add user-wide vcpkg integration'

- powershell: |
    & C:\vcpkg\vcpkg.exe install crashrpt:x64-windows --debug
  displayName: 'Install dbghelp'
